import type { Personality, Report } from "./types";

export const seedPersonalities: Personality[] = [
  {
    id: "p_sage",
    name: "Sage",
    tagline: "A calm, contemplative thinker",
    description:
      "Sage helps you reflect on ideas, explore philosophy, and find clarity in complex problems through thoughtful conversation.",
    avatar: "S",
    category: "Wellness",
    rating: 4.9,
    chats: 12_420,
    isPublic: true,
    systemPrompt: "You are Sage, a calm and thoughtful AI focused on reflection and clarity.",
    creator: { id: "u_core", name: "CoreChat", avatar: "C" },
    createdAt: new Date(2025, 1, 12).toISOString(),
  },
  {
    id: "p_atlas",
    name: "Atlas",
    tagline: "Senior software architect",
    description:
      "Atlas is a pragmatic engineering mentor with deep knowledge of TypeScript, distributed systems, and product thinking.",
    avatar: "A",
    category: "Engineering",
    rating: 4.8,
    chats: 9_120,
    isPublic: true,
    systemPrompt: "You are Atlas, a senior software architect. Be precise, concise, and pragmatic.",
    creator: { id: "u_core", name: "CoreChat", avatar: "C" },
    createdAt: new Date(2025, 2, 3).toISOString(),
  },
  {
    id: "p_nova",
    name: "Nova",
    tagline: "Creative writing partner",
    description:
      "Nova co-writes stories, refines prose, and helps you push past the blank page with vivid imagination.",
    avatar: "N",
    category: "Writing",
    rating: 4.7,
    chats: 7_540,
    isPublic: true,
    systemPrompt: "You are Nova, an imaginative co-writer with a poetic, vivid voice.",
    creator: { id: "u_core", name: "CoreChat", avatar: "C" },
    createdAt: new Date(2025, 3, 18).toISOString(),
  },
  {
    id: "p_orion",
    name: "Orion",
    tagline: "Strategy & business coach",
    description:
      "Orion helps founders and operators stress-test plans, sharpen positioning, and make decisions under uncertainty.",
    avatar: "O",
    category: "Business",
    rating: 4.6,
    chats: 5_980,
    isPublic: true,
    systemPrompt: "You are Orion, a sharp business strategist. Ask probing questions.",
    creator: { id: "u_core", name: "CoreChat", avatar: "C" },
    createdAt: new Date(2025, 4, 22).toISOString(),
  },
  {
    id: "p_lumen",
    name: "Lumen",
    tagline: "Personal learning tutor",
    description:
      "Lumen patiently explains anything — math, languages, science — using examples adapted to how you learn.",
    avatar: "L",
    category: "Education",
    rating: 4.8,
    chats: 8_310,
    isPublic: true,
    systemPrompt: "You are Lumen, a patient tutor that uses analogies and Socratic questions.",
    creator: { id: "u_core", name: "CoreChat", avatar: "C" },
    createdAt: new Date(2025, 5, 1).toISOString(),
  },
  {
    id: "p_kai",
    name: "Kai",
    tagline: "Fitness & habits coach",
    description:
      "Kai designs realistic routines, tracks habits, and keeps you honest without ever being preachy.",
    avatar: "K",
    category: "Wellness",
    rating: 4.5,
    chats: 4_220,
    isPublic: false,
    systemPrompt: "You are Kai, a no-nonsense but supportive fitness and habit coach.",
    creator: { id: "u_you", name: "You", avatar: "Y" },
    createdAt: new Date(2025, 5, 14).toISOString(),
  },
];

export const seedReport: Report = {
  totalChats: 142,
  totalMessages: 1_864,
  tokensUsed: 412_300,
  favoritePersonality: "Atlas",
  dailyActivity: [
    { day: "Mon", chats: 6, messages: 84 },
    { day: "Tue", chats: 9, messages: 121 },
    { day: "Wed", chats: 4, messages: 52 },
    { day: "Thu", chats: 12, messages: 168 },
    { day: "Fri", chats: 8, messages: 96 },
    { day: "Sat", chats: 3, messages: 41 },
    { day: "Sun", chats: 5, messages: 63 },
  ],
  categoryUsage: [
    { name: "Engineering", value: 42 },
    { name: "Writing", value: 24 },
    { name: "Wellness", value: 18 },
    { name: "Business", value: 11 },
    { name: "Education", value: 5 },
  ],
  achievements: [
    {
      id: "a_first_chat",
      title: "First Spark",
      description: "Started your first conversation.",
      unlocked: true,
      progress: 1,
      goal: 1,
    },
    {
      id: "a_century",
      title: "Century Club",
      description: "Sent 100 messages.",
      unlocked: true,
      progress: 100,
      goal: 100,
    },
    {
      id: "a_personality_creator",
      title: "Personality Architect",
      description: "Created your first AI personality.",
      unlocked: true,
      progress: 1,
      goal: 1,
    },
    {
      id: "a_streak_7",
      title: "7-Day Streak",
      description: "Chat for 7 days in a row.",
      unlocked: false,
      progress: 4,
      goal: 7,
    },
    {
      id: "a_polyglot",
      title: "Polyglot",
      description: "Chat in 5 different languages.",
      unlocked: false,
      progress: 2,
      goal: 5,
    },
  ],
};
