/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SignupRouteImport } from './routes/signup'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AppRouteImport } from './routes/_app'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppSettingsRouteImport } from './routes/_app.settings'
import { Route as AppReportsRouteImport } from './routes/_app.reports'
import { Route as AppChatRouteImport } from './routes/_app.chat'
import { Route as AppPersonalitiesIndexRouteImport } from './routes/_app.personalities.index'
import { Route as AppPersonalitiesNewRouteImport } from './routes/_app.personalities.new'
import { Route as AppPersonalitiesIdRouteImport } from './routes/_app.personalities.$id'

const SignupRoute = SignupRouteImport.update({
  id: '/signup',
  path: '/signup',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppSettingsRoute = AppSettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => AppRoute,
} as any)
const AppReportsRoute = AppReportsRouteImport.update({
  id: '/reports',
  path: '/reports',
  getParentRoute: () => AppRoute,
} as any)
const AppChatRoute = AppChatRouteImport.update({
  id: '/chat',
  path: '/chat',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalitiesIndexRoute = AppPersonalitiesIndexRouteImport.update({
  id: '/personalities/',
  path: '/personalities/',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalitiesNewRoute = AppPersonalitiesNewRouteImport.update({
  id: '/personalities/new',
  path: '/personalities/new',
  getParentRoute: () => AppRoute,
} as any)
const AppPersonalitiesIdRoute = AppPersonalitiesIdRouteImport.update({
  id: '/personalities/$id',
  path: '/personalities/$id',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/personalities/$id': typeof AppPersonalitiesIdRoute
  '/personalities/new': typeof AppPersonalitiesNewRoute
  '/personalities/': typeof AppPersonalitiesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/chat': typeof AppChatRoute
  '/reports': typeof AppReportsRoute
  '/settings': typeof AppSettingsRoute
  '/personalities/$id': typeof AppPersonalitiesIdRoute
  '/personalities/new': typeof AppPersonalitiesNewRoute
  '/personalities': typeof AppPersonalitiesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_app': typeof AppRouteWithChildren
  '/login': typeof LoginRoute
  '/signup': typeof SignupRoute
  '/_app/chat': typeof AppChatRoute
  '/_app/reports': typeof AppReportsRoute
  '/_app/settings': typeof AppSettingsRoute
  '/_app/personalities/$id': typeof AppPersonalitiesIdRoute
  '/_app/personalities/new': typeof AppPersonalitiesNewRoute
  '/_app/personalities/': typeof AppPersonalitiesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/reports'
    | '/settings'
    | '/personalities/$id'
    | '/personalities/new'
    | '/personalities/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/signup'
    | '/chat'
    | '/reports'
    | '/settings'
    | '/personalities/$id'
    | '/personalities/new'
    | '/personalities'
  id:
    | '__root__'
    | '/'
    | '/_app'
    | '/login'
    | '/signup'
    | '/_app/chat'
    | '/_app/reports'
    | '/_app/settings'
    | '/_app/personalities/$id'
    | '/_app/personalities/new'
    | '/_app/personalities/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRoute: typeof AppRouteWithChildren
  LoginRoute: typeof LoginRoute
  SignupRoute: typeof SignupRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/signup': {
      id: '/signup'
      path: '/signup'
      fullPath: '/signup'
      preLoaderRoute: typeof SignupRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/settings': {
      id: '/_app/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof AppSettingsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/reports': {
      id: '/_app/reports'
      path: '/reports'
      fullPath: '/reports'
      preLoaderRoute: typeof AppReportsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/chat': {
      id: '/_app/chat'
      path: '/chat'
      fullPath: '/chat'
      preLoaderRoute: typeof AppChatRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personalities/': {
      id: '/_app/personalities/'
      path: '/personalities'
      fullPath: '/personalities/'
      preLoaderRoute: typeof AppPersonalitiesIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personalities/new': {
      id: '/_app/personalities/new'
      path: '/personalities/new'
      fullPath: '/personalities/new'
      preLoaderRoute: typeof AppPersonalitiesNewRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/personalities/$id': {
      id: '/_app/personalities/$id'
      path: '/personalities/$id'
      fullPath: '/personalities/$id'
      preLoaderRoute: typeof AppPersonalitiesIdRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppChatRoute: typeof AppChatRoute
  AppReportsRoute: typeof AppReportsRoute
  AppSettingsRoute: typeof AppSettingsRoute
  AppPersonalitiesIdRoute: typeof AppPersonalitiesIdRoute
  AppPersonalitiesNewRoute: typeof AppPersonalitiesNewRoute
  AppPersonalitiesIndexRoute: typeof AppPersonalitiesIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppChatRoute: AppChatRoute,
  AppReportsRoute: AppReportsRoute,
  AppSettingsRoute: AppSettingsRoute,
  AppPersonalitiesIdRoute: AppPersonalitiesIdRoute,
  AppPersonalitiesNewRoute: AppPersonalitiesNewRoute,
  AppPersonalitiesIndexRoute: AppPersonalitiesIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRoute: AppRouteWithChildren,
  LoginRoute: LoginRoute,
  SignupRoute: SignupRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
